version: '3.8'

services:
  test-app:
    image: tcnichol/test:latest  # Use 'latest' or a specific tag you want to track
    container_name: test-container
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"