version: '3.8'

services:
  test-app:
    image: tcnichol/test:${VERSION_NUMBER}  # Initial version
    container_name: test-container
    restart: unless-stopped
    environment:
      - DOCKERHUB_USER=${DOCKERHUB_USER}
      - DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN}