name: Check for Image Updates Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allow manual triggering

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get current image digest
        id: current-image
        run: |
          docker pull tcnichol/test:latest || true  # Pull or continue if missing
          CURRENT_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' tcnichol/test:latest 2>/dev/null || echo "none")
          echo "CURRENT_DIGEST=${CURRENT_DIGEST}" >> $GITHUB_ENV

      - name: Pull latest image
        run: docker pull tcnichol/test:latest

      - name: Get new image digest
        id: new-image
        run: |
          NEW_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' tcnichol/test:latest)
          echo "NEW_DIGEST=${NEW_DIGEST}" >> $GITHUB_ENV

      - name: Restart if digest changed
        if: env.CURRENT_DIGEST != env.NEW_DIGEST
        run: |
          docker-compose down
          docker-compose up -d
          echo "🔄 Container restarted with new image (Digest: ${{ env.NEW_DIGEST }})"