name: Docker Image Auto-Update

on:
  schedule:
    - cron: '*/5 * * * *'  # Checks every 5 minutes
  workflow_dispatch:       # Manual trigger option

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Check for image updates
        id: image-check
        run: |
          OLD_DIGEST=$(docker inspect --format '{{.RepoDigests}}' tcnichol/test:latest 2>/dev/null || echo "none")
          docker pull tcnichol/test:latest
          NEW_DIGEST=$(docker inspect --format '{{index .RepoDigests 0}}' tcnichol/test:latest)
          echo "old_digest=$OLD_DIGEST" >> $GITHUB_OUTPUT
          echo "new_digest=$NEW_DIGEST" >> $GITHUB_OUTPUT

      - name: Restart if changed
        if: steps.image-check.outputs.old_digest != steps.image-check.outputs.new_digest
        run: |
          docker-compose down
          docker-compose up -d
          echo "Container updated to new image version"er restarted with new image (Digest: ${{ env.NEW_DIGEST }})"