name: Deploy and Update Container

on:
  push:
    tags:
      - 'v*'  # Trigger when you push version tags (like v1.0.1)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull latest image
        run: |
          docker-compose pull test-app

      - name: Redeploy containers
        run: |
          docker-compose up -d