name: Update Docker Deployment

on:
  push:
    tags:
      - 'v*'  # Trigger when you push version tags like v1.0.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose-plugin

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Update and Redeploy
        run: |
          # Get the new version tag (e.g. v1.0.1)
          NEW_VERSION=${GITHUB_REF#refs/tags/}
          
          # Update compose file with new version
          sed -i "s|image: tcnichol/test:v.*|image: tcnichol/test:$NEW_VERSION|" docker-compose.yml
          
          # Pull new image and redeploy
          docker-compose pull
          docker-compose up -d --force-recreate
          
          # Clean up old containers and images
          docker system prune -f