name: Update Docker Container

on:
  push:
    tags:
      - 'v*'  # Trigger when you push a version tag
    branches:
      - main  # Optional: also trigger on main branch pushes

jobs:
  update-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Pull latest image
      run: docker pull tcnichol/test:latest

    - name: Stop and restart containers
      run: |
        cd /path/to/your/docker-compose/directory
        docker-compose down
        docker-compose up -d