name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify secrets are available
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
            echo "::error::DOCKER_HUB_USERNAME secret is missing"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
            echo "::error::DOCKER_HUB_TOKEN secret is missing"
            exit 1
          fi
          echo "Secrets are available (username length: ${#{{ secrets.DOCKER_HUB_USERNAME }}}, token length: ${#{{ secrets.DOCKER_HUB_TOKEN }}})"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub (with debug output)
        id: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        env:
          ACTIONS_STEP_DEBUG: true  # Enable debug output

      - name: Verify Docker Hub authentication
        run: |
          echo "Checking Docker credentials..."
          cat ~/.docker/config.json
          echo "Attempting to access repository..."
          docker pull hello-world
          echo "Authentication seems successful!"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tcnichol/test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max