name: Docker Build and Push

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "Username exists: ${{ secrets.DOCKER_HUB_USERNAME != '' }}"
          echo "Token exists: ${{ secrets.DOCKER_HUB_TOKEN != '' }}"
          echo "Repo: tcnichol/test"

      - name: Pure Docker Login Test
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}" \
            --password-stdin
          docker info

      - name: Build and Push (Simplified)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tcnichol/test:manual-test-1
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}