name: Test SSH Connection

on:
  push:
    branches: [ main ]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "echo '✅ Successfully connected to $(hostname)'"